#!/bin/bash
# This script configures UFW to allow essential ports and forward traffic from TCP 8080 to TCP 80

apt-get update -y
apt-get install ufw -y

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

sed -i 's/#net\/ipv4\/ip_forward=1/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf

ufw_before_rules="/etc/ufw/before.rules"
cp $ufw_before_rules "${ufw_before_rules}.bak"

if ! grep -q "REDIRECT --to-port 80" "$ufw_before_rules"; then
    sed -i '1i*nat\n:PREROUTING ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n' "$ufw_before_rules"
fi

sysctl -p
ufw disable
ufw enable

ufw status verbose
grep -A5 REDIRECT /etc/ufw/before.rules

