#!/usr/bin/env bash
## Ensure Nginx is installed and listening on port 80 on all IPv6 interfaces
apt-get update -y
apt-get install -y nginx

# Replace default config to ensure it listens correctly
cat > /etc/nginx/sites-enabled/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx to apply changes
systemctl restart nginx
