#!/usr/bin/env bash
# configure Nginx to listen on port 80 on all IPv4 interfaces

rm /etc/nginx/sites-enable/default
cd /etc/nginx/sites-enable/default
ln -s ../sites-available/default .
service ngnix restart 
curl 0:80
