#!/usr/bin/env bash
# Transfers a file to a remote server using scp with provided SSH key and credentials

# Check number of arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file to the remote user's home directory
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"

